<?php
 /**
  * Title: Mailchimp Signup
  * Slug: the-territory/signup
  * Categories: the-territory
  */
?>

<!-- wp:group {"className":"signup"} -->
<div class="wp-block-group signup WATWAT">
    <!-- wp:heading -->
    <h2><?php esc_html_e( 'Let\'s Work Together', 'our-forests' ); ?></h2>
    <!-- /wp:heading -->

    <!-- wp:paragraph -->
    <p><?php esc_html_e( 'Sign up to receive updates about upcoming screenings of The Territory,<br>as well as our impact efforts around the world.', 'our-forests' ); ?></p>
    <!-- /wp:paragraph -->

    <!-- wp:yikes-inc-easy-forms/easy-forms-block {"form_id":"1","form":{"custom_fields":[],"custom_notifications":"","custom_styles":"","custom_template":0,"error_messages":{"success":"","success-single-optin":"","success-resubscribed":"","general-error":"","already-subscribed":"","update-link":"","email-subject":"","email-body":"Greetings,\r\n\r\nA request has been made to update your Mailchimp account profile information. To do so please use the following link: [link]Update Mailchimp Profile Info[/link]\r\n\r\nIf you did not request this update, please disregard this email.\r\n\r\n\u0026nbsp;\r\n\r\nThis email was sent from: [url]\r\n\r\n\u0026nbsp;\r\n\r\n\u0026nbsp;\r\n\u003cp style=\u0022font-size: 13px; margin-top: 5em;\u0022\u003e\u003cem\u003eThis email was generated by the \u003ca href=\u0022http://www.wordpress.org/plugins/yikes-inc-easy-mailchimp-extender/\u0022 target=\u0022_blank\u0022 rel=\u0022noopener\u0022\u003eEasy Forms for Mailchimp\u003c/a\u003e plugin, created by \u003ca href=\u0022http://www.yikesinc.com\u0022 target=\u0022_blank\u0022 rel=\u0022noopener\u0022\u003eYIKES Inc.\u003c/a\u003e\u003c/em\u003e\u003c/p\u003e","update-email-success":"","update-email-failure":""},"fields":{"FNAME":{"label":"First Name","type":"text","merge":"FNAME","position":"1","id":"1","placeholder":"First Name","default":"","description":"","additional-classes":""},"LNAME":{"label":"Last Name","type":"text","merge":"LNAME","position":"2","id":"2","placeholder":"Last Name","default":"","description":"","additional-classes":""},"EMAIL":{"label":"Email Address","type":"email","merge":"EMAIL","position":"3","id":"0","placeholder":"Email","default":"","description":"","additional-classes":""}},"form_description":"","form_name":"Sign-up","form_settings":{"yikes-easy-mc-form-class-names":"","yikes-easy-mc-inline-form":"0","yikes-easy-mc-submit-button-type":"text","yikes-easy-mc-submit-button-text":"Submit","yikes-easy-mc-submit-button-image":"","yikes-easy-mc-submit-button-classes":"","yikes-easy-mc-form-schedule":"0","yikes-easy-mc-form-restriction-start":1657920540,"yikes-easy-mc-form-restriction-end":1657920540,"yikes-easy-mc-form-restriction-pending-message":"Signup is not yet open, and will be available on July 15, 2022 at 5:28PM. Please come back then to signup.","yikes-easy-mc-form-restriction-expired-message":"This signup for this form ended on July 16, 2022 at 5:28PM.","yikes-easy-mc-form-login-required":"0","yikes-easy-mc-form-restriction-login-message":"You need to be logged in to sign up for this mailing list."},"id":1,"impressions":46,"list_id":"502b548b1f","optin_settings":{"optin":"1","update_existing_user":"1","send_update_email":"1"},"redirect_page":"137","redirect_user_on_submit":"0","submission_settings":{"ajax":"1","redirect_on_submission":"0","redirect_page":"137","hide_form_post_signup":"0","custom_redirect_url":"","redirect_new_window":"0","replace_interests":"1"},"submissions":0},"form_title":"Sign-up","submit_button_text":"Sign Up"} /-->
</div>
<!-- /wp:group -->
